// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkExchange_API.Models;

public partial class Blacklists
{
    public int Id { get; set; }

    public int BlockerId { get; set; }

    public int BlockedId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Users Blocked { get; set; } = null!;

    public virtual Users Blocker { get; set; } = null!;
}