// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
namespace WorkExchange_API.Models;

public partial class ChatMessage
{
    public int Id { get; set; }

    public int? RoomId { get; set; }

    public int? SenderUserId { get; set; }

    public string? Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public bool IsRead { get; set; }

    public virtual ChatRoom? Room { get; set; }

    public virtual Users? SenderUser { get; set; }

    [NotMapped]
    public bool IsFirstUnread { get; set; }
}