// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace WorkExchange_API.Models;

public partial class ChatRoom
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public int? HostId { get; set; }

    public string? LastMessagePreview { get; set; }

    public int? Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? LastMessageAt { get; set; }

    public DateTime? UserLastReadAt { get; set; }

    public DateTime? HostLastReadAt { get; set; }

    public virtual ICollection<ChatMessage> ChatMessage { get; set; } = new List<ChatMessage>();

    public virtual Users? Host { get; set; }

    public virtual Users? User { get; set; }
}